### ISSUE TITLE
Not being proxies properly.

### ISSUE THREAD

**Issue by c4p-n1ck** [wjhoward/brachyura#4]
All I get is `404` :confused: and I see that the requests are not being made in the first place. 
Let me know, if you need more info (do include what all I'm supposed to share)

**Comment by wjhoward** [comment]
Thanks for raising an issue. How are you testing this? Are you able to run `cargo test --lib` ? `cargo test` should also work assuming you have configured a test TLS key and cert.

I have noticed that when testing with curl and HTTP2, the host header was not accessible via `req.headers()` and using a default host header (when one was not set) was confusing things, so I've since removed the default host header code.
I need to fix the code to properly handle the Host header for HTTP2 (a pseudo header).

**Comment by wjhoward** [comment]
@c4p-n1ck I've made various changes to the code since this issue was raised, so it would be good to get more information, and to know if the issue you are encountering still exists.
